### ISSUE TITLE
Why does it only knit when folder is named index?

### ISSUE THREAD

**Issue by georoen** [ismayc/thesisdown#10]
Hi,
I'm looking forwards using your package. Now I'm busy integrating it into my folder structure and would really prefer naming the folder `text` or something else. But as you point out in README.md line 35 it's necessary to name it `index`. I'd love to contribute to your package, so I though you could provide me some infos about this?

**Comment by ismayc** [comment]
Great!  You can rename the folder to something different than `index` but the main file needs to be named `index.Rmd` so that it builds an `index.html` file if you'd like a webpage version of your thesis.
