### ISSUE TITLE
Headheight issue in old pdf template

### ISSUE THREAD

**Issue by abichat** [ismayc/thesisdown#102]
I'm working with an old (< May 2020) template of thesisdown and I struggle to fix the headheight issue (as in #86).

I added `\addtolength\headheight{2.5pt}` in the `.cls` file as in your [commit](https://github.com/ismayc/thesisdown/commit/9bf78a3be301bcca0e9d7674e3259522dca268f7#diff-3f658befca3a78b32e9c34d63b5a4b20R188) but it does not solve the problem, I still have the following error message:

```
Package Fancyhdr Warning: \headheight is too small (0.0pt): 
Make it at least 14.49998pt.
We now make it that large for the rest of the document.
This may cause the page layout to be inconsistent, however. 
```

Is there something else to change? (I already fixed the issues for the gitbook output by removing the space)

**Comment by ismayc** [comment]
I'm not aware of anything else to change. Could you share a minimally reproducible example of the files you are using and I can try to track down the error?

**Comment by abichat** [comment]
I have done a test for deployment [here](https://github.com/abichat/testdeploybook), with hadamardown and a thesisdown template from 5 months ago. 
As you can [see](https://github.com/abichat/testdeploybook/runs/909427230?check_suite_focus=true#step:8:697), the error is still there.

**Comment by ismayc** [comment]
While a little tedious to go through the files and see what has changed compared to the `develop` branch files, [this PR](https://github.com/ismayc/thesisdown/pull/104/files) where I loaded in your files and isolated on `template.tex` was helpful for me to see what might be causing the error.

**Comment by abichat** [comment]
This works perfectly! Thanks a lot for taking the time to fix my issue 👍
