### ISSUE TITLE
Add declaration of authorship after bibliography

### ISSUE THREAD

**Issue by MarkusBerroth** [ismayc/thesisdown#107]
First of all, thanks for the great template.

However, my university requests a declaration of authorship as the last page. 
I created a new .Rmd file and added it to the .yml after the references file.
`rmd_files: ["index.Rmd", "01-introduction.Rmd", "02-cpater.Rmd", "07-conclusion.Rmd", "10-appendix.Rmd", "99-references.Rmd", "100-declaration.Rmd"]`

However, it renders first the references header, then the declaration and afterwards all the bibliography entries.  
So, it is not on the last page, but within the bibliography. 
I also tried to include it as a separate .pdf file with the same result. 

Is there the possibility to add something after the bibliography entries? 

Thank you in advance!

**Comment by ismayc** [comment]
You're welcome!

Unfortunately, I can't figure out a way to get `rmd_files` to work with {thesisdown} in the .yml file as you have tried. It appears there is something within the RStudio interface that is happening differently when one presses Knit for {thesisdown} compared to pressing Build for {bookdown} and I can't figure out exactly what that is or ways that a function could be called instead.

Can you try only placing the Rmd files that you are using to build your thesis in your main directory in the order you'd like them to appear and removing any other ones? This should be a good first step to potentially get this working.

I haven't tried [this](https://stackoverflow.com/a/44294306/6242384) with PDF output, but others have had success with adding `<div id="refs"></div>` after `# References` to force the bibliography to appear there and for other items to follow.

**Comment by abichat** [comment]
As @ismayc suggested, `<div id="refs"></div>` works as expected for the html version.

For the pdf, you can add a section like 
```
$if(declaration)$
  \begin{declaration}
    $declaration$
  \end{declaration}
$endif$
```
after the `$body$` in your `template.tex` file. 
It requires some modifications in the `.cls` file and in the YAML options but it is virtually a transposition of the `acknowledgements` or `dedication` sections. 

If you want to have both outputs, don't put `100-declaration.Rmd` in the `rmd_files` argument but instead use it like this 
```
`r if(!knitr::is_latex_output()) paste(readLines("100-declaration.Rmd"), collapse = '\n  ')`
```
after the `<div id="refs"></div>` so the `declaration` section is called in the `99-references.Rmd` file for the html output and in the `template.tex` file for the pdf one.

**Comment by ismayc** [comment]
@MarkusBerroth Did we answer your question here? I'll assume so unless I see differently.

**Comment by MarkusBerroth** [comment]
Hey,
sorry I forgot totally to respond.

In my case even for the PDF version the trick with adding `<div id="refs"></div>` worked. 
Thank you very much for your help! Everything worked out great.
