### ISSUE TITLE
Deprecated argument

### ISSUE THREAD

**Issue by keurcien** [ismayc/thesisdown#11]
Hi,

Thanks for sharing your template, it is very neat. 
Just to mention that the pandoc argument chapters is now deprecated and should be replaced with
pandoc_args = "--top-level-division=chapter". By the way, if you want to provide a French template, I can send my modified version to you. Otherwise I could share it on my Github and put your name in the references.

Cheers,

Keurcien

**Comment by ismayc** [comment]
Thanks!  I will make this change.  If you could send along a link to your template on GitHub, I will add it in some way going forward.

**Comment by keurcien** [comment]
Sure, here it is: https://github.com/keurcien/tmp/tree/master/index
I have changed a couple of things but to have it in French, it essentially consists in including \usepackage[french]{babel} in the template.tex file, and translating the different sections name (Aknowledgements to Remerciements, Preface to Préface, ...). 

I got another warning though, about the bibtex exiting with status 1 (even without my modifications) Using the Reed Senior thesis template does not trigger the error, but doing this with the Thesis template does, while I can't seem to find any difference between these two. The pandoc commands are identical.
I'll let you know if I find out about what's going on, but if you have come accross this one already, that'd be great :D

**Comment by keurcien** [comment]
Update:

All I wrote was related to my Windows OS.
On my OSX everything works fine, though it is not based on the latest version of pandoc (so I use argument --chapters on my Macintosh and "--top-level-division=chapter" on Windows)

Cheers.

**Comment by ismayc** [comment]
Thanks.  I'm hardly ever on Windows anymore so this is a helpful tip.

**Comment by paynito** [comment]
Also getting the --chapters message, but it isn't fatal.  What's killing me is

    ! FancyVerb Error:
  Empty verbatim environment
   \FV@Error ... {FancyVerb Error:
   \space \space #1
    }

I think the fix is 

    header-includes: \VerbatimFootnotes ## to fix fancy verb error 

Maybe that should go in R/thesis.R as a pandoc argument?  or is it LaTeX?  I can't seem to edit the files directly in ~/Rlibs.

**Comment by ismayc** [comment]
I'm not able to reproduce this error.  Can you provide more details or a link to your repo?

**Comment by ismayc** [comment]
I believe this is a LaTeX error on first glance.  I'd recommend reinstalling LaTeX and the necessary packages.

**Comment by paynito** [comment]
Thank you, I think it's happening when I have an ```{r} #empty ``` block where I commented out all the code. thus "empty verbatim environment" but I'm not always able to track it down.

**Comment by ismayc** [comment]
@keurcien Could you make a pull request to make the change to the deprecated argument?  Thanks.

**Comment by ismayc** [comment]
@nicksolomon Can you look into making this change to `pandoc_args = "--top-level-division=chapter"` that @keurcien originally referenced here?

**Comment by nicksolomon** [comment]
I think we should hold off on this. The argument `top-level-division` is from Pandoc v. 1.19.2 (I think) but RStudio ships with version 1.17.2. The deprecated error only shows up if the user has installed a more recent version of Pandoc on their own. However, trying to use `top-level-division` with RStudio out of the box throws an error. See rstudio/bookdown#365
