### ISSUE TITLE
Reload in Sumatra does not work with output thesisdown::thesis_pdf: default

### ISSUE THREAD

**Issue by Famondir** [ismayc/thesisdown#112]
HI,
I just started wo work with thesisdown. Thanks for your work! But I found that rebuildung the thesis does not refresh the PDF view in Sumatra using the output type `thesisdown::thesis_pdf: default`. But automatic reloading works with output type `pdf_document` or `thesisdown::thesis_gitbook: default`.

So it seems to be an special issue with the output type `thesisdown::thesis_pdf: default`, doesn't it?

I'm using RStudio 1.3.1037, Win10 x64 18363, pandoc 2.7.3, R 4.0.3.

**Comment by Famondir** [comment]
Issue still remains with all pandoc versions I tried. (2.8.1, 2.9.2.1, 2.10.2 and 2.11.1).

**Comment by ismayc** [comment]
Hi there. I'm trying to track down a way to simulate this given I only have access to a Mac. Can you confirm it doesn't work with different PDF viewers like Adobe Acrobat too?

**Comment by ismayc** [comment]
If that's not really possible or too much of a pain, could you share a Loom screen recording (audio not necessary) so I can better understand what you are seeing.

**Comment by Famondir** [comment]
Here is a loom:
https://www.loom.com/share/e9ea2c6345f043d9bc4d08d3fcb09944

I'll have a look if I can link another PDF viewer with RStudio.

**Comment by ismayc** [comment]
Thanks again for the very helpful Loom video! That definitely is annoying. I'm still looking into what might be causing this. Thanks for your patience!

**Comment by ismayc** [comment]
Unfortunately, I can't get this behavior of auto-syncing back with where the file was edited with the default RStudio PDF viewer for `bookdown::pdf_book` or `thesisdown::thesis_pdf`. I'm not sure if there will be a solution to your issue because of this as it looks like it is something that Sumatra does?

**Comment by ismayc** [comment]
Hmmph, I'm at a loss here. It looks like SyncTex should work on the Mac I am on, but it isn't: https://support.rstudio.com/hc/en-us/articles/200552066-PDF-Preview-and-SyncTeX
