### ISSUE TITLE
thesisdown does not work with pandoc 2.11+

### ISSUE THREAD

**Issue by Famondir** [ismayc/thesisdown#113]
I found that thesisdown does not work with the latest pandoc versions when making PDFs. Until version 2.10.1 it works fine. Then it states an issue about the `cslreferences`.

**Comment by danieltomasz** [comment]
I have pandoc_version() =  ‘2.11.1.1’

I am getting `! LaTeX Error: Environment CSLReferences undefined.` when trying to complie

Using   "CSLreferences" instead "cslreferences" in the code defined in template solve the issue

```
%Added by @MyKo101, code provided by @GerbrichFerdinands
$if(csl-refs)$
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newenvironment{CSLReferences}%
  {$if(csl-hanging-indent)$\setlength{\parindent}{0pt}%
  \everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces$endif$}%
  {\par}
$endif$
```

**Comment by Famondir** [comment]
I confirm this solved the problem.
