### ISSUE TITLE
add beardown to readme.md

### ISSUE THREAD

**Issue by kelseygonzalez** [ismayc/thesisdown#114]
Recently developed the University of Arizona version of thesisdown aptly titled, `beardown` (the schools motto). 

Because I developed the package on a fork of thesis down, that means I can't do a PR as requested in the readme.md without adding a new branch and reseting the branch (or something along those lines).

Therefore, could you add this to the readme.md?

```
| University of Arizona | [kelseygonzalez/beardown](https://github.com/kelseygonzalez/beardown) |[ismayc/thesisdown](https://github.com/ismayc/thesisdown) |
```

Many thanks for a great package, @ismayc !

**Comment by ismayc** [comment]
Nice! I did my PhD at Arizona State (don't judge me 😄 ) so I know Bear Down well 👍 . Thanks for adding (should be visible now) and you're welcome!
