### ISSUE TITLE
PDF sections not numbered from toc depth 4

### ISSUE THREAD

**Issue by pcastellanoescuder** [ismayc/thesisdown#116]
Hello!

I'm trying to render my thesis (in PDF format) with a toc depth = 4 using the simple following code in my YAML header:

```{r}
output:
  thesisdown::thesis_pdf:
    toc_depth: 4
```

However, seems that neither the index nor the body document have the correct structure for the sections from toc 4. Moreover, the same wrong structured sections don't present their own section number...

Do you know how I can number and structure well all my sections (even from toc depth 4)??

Thanks:)

**Comment by ismayc** [comment]
Hi there. Just to make sure I understand your request could you provide some examples of what you'd like the output to look like?

**Comment by pcastellanoescuder** [comment]
By introducing the code I have mentioned in my index.Rmd I'm getting this output. As you can see, only sections with a toc 1, 2 or 3 are well structured and numbered. Otherwise, sections with a depth of 4 are in the same level of toc 3 sections and aren't numbered.

<img width="897" alt="wrong_toc" src="https://user-images.githubusercontent.com/38317483/100901547-39081f00-34c4-11eb-8a3d-ec79ada87df0.png">

Thanks:)

**Comment by ismayc** [comment]
I've updated the master branch with an update to fix this. If you add in [the following line](https://github.com/ismayc/thesisdown/blob/49a97329d9d71da7764ad5ec3cb414818909b025/inst/rmarkdown/templates/thesis/skeleton/template.tex#L189) to template.tex, it should be working for you too. I'm going to close this issue but feel free to reopen if it isn't working for you. Thanks for reporting!

**Comment by pcastellanoescuder** [comment]
Solved! Thanks a lot!
