### ISSUE TITLE
cannot open file 'index.Rmd'

### ISSUE THREAD

**Issue by pat-s** [ismayc/thesisdown#12]
When knitting the template on a fresh install I get the following:

```
Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> ... mapply -> <Anonymous> -> readUTF8 -> readLines -> file
In addition: Warning message:
In file(con, "r") : cannot open file 'index.Rmd': No such file or directory
Execution halted
```

Removing `index.Rmd` from `_bookdown.yml` clears the issue :)

Thanks for this great package :smiley:

**Comment by ismayc** [comment]
If you want to set your thesis as a webpage you need to have an `index.Rmd` driver file.  The README for this package explains this rule.

**Comment by pat-s** [comment]
Oh damn, sorry for being lazy and not reading the README/closed issues before asking :no_mouth:
