### ISSUE TITLE
Chapter 3 template preventing knitting

### ISSUE THREAD

**Issue by kelseygonzalez** [ismayc/thesisdown#122]
**Describe the bug**
When rendering the default template, there's something in chapter 3 that Latex is now struggling to render that is breaking the build. 

**To Reproduce**
Create a new thesisdown from the template, and click knit from the index.Rmd file. Error from the console / thesis.log:
```
Chapter 3.
! Missing number, treated as zero.
<to be read again> 
                   (
l.553 ...columnwidth - 2\tabcolsep) * \real{0.31}}
                                                  \centering 
```

**Expected behavior**
I expect it to render the default document. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version  R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"

**Additional context**
This could definitely be a latex issue on my own computer. I've been fighting with it all day but this error has persisted. If I delete most of the chapter 3, the error disappears and the document renders.

**Comment by ismayc** [comment]
Hi there. I think this might be the table that I have added in to demo that in Chapter 3 as that has caused issues with LaTeX before. It's probably best to just remove that Markdown table and generate tables with R instead.

**Comment by kelseygonzalez** [comment]
Indeed @ismayc  - I just tested by removing only the markdown table at the beginning and it rendered. Sounds like it's time to rid ourselves of that pesky table!

**Comment by ismayc** [comment]
I'll look into updating the template over the next few days so others don't have this same issue when they do a fresh build. Thanks for reporting!

**Comment by Xyv** [comment]
Hey,
Pandoc has recently changed the way they compute the the column widths in tables: https://github.com/jgm/pandoc/commit/bd7c9eb32be7c5499f4a50cb4b5f138f9eb919e8
Adding `\usepackage{calc}` in the template fixes this.
And thanks for all the work you've done!

**Comment by Xyv** [comment]
My pleasure, happy to be of some help to this nice project.

**Comment by ismayc** [comment]
Pushed to `master` in #124
