### ISSUE TITLE
Change appearance of links in pdf

### ISSUE THREAD

**Issue by LGurtner** [ismayc/thesisdown#123]
Hello, 

first of all, thank you so much for this great package! Writing my PhD with it has been such a smooth experience! 
I am now printing my Thesis and I would like to change a minor thing in it: All links (DOIs but also links to other chapters, figures etc) have a colored frame around them which highlights them as a link. That's perfect in the digital version, but not for printing, since every page with a colored frame on it will cost the price of a color print instead of a black and white print. How can I change this? I feel like this should involve some tweaking of a .css file but I can't find one and I would not know what exactly to change. So I really have two questions: 

1. Where can I find the css file that manages the appearance in the PDF?
2. What would I have to change in this file to make the links monochrome or white? 
Thank you again for the package and for your help here!

**Comment by LGurtner** [comment]
Ok, I just found a cls file which might be what I need (hiding in plain sight as reedthesis.cls in the main directory). 
As for my second question, I'm a little clueless. Will continue searching but if you know the quick fix, please let me know, thank you!

**Comment by LGurtner** [comment]
I found the answer [here](https://stackoverflow.com/questions/44846350/how-to-set-colour-for-toc-links-in-r-markdown-document), no messing with the cls needed, only an addition to the YAML header: 

```
header-includes:
    - \usepackage {hyperref}
    - \hypersetup {colorlinks = true, linkcolor = black, urlcolor = black}
```

**Comment by ismayc** [comment]
Thanks for sharing! Sorry it took me a bit to get to this but I'm glad you found a solution.

**Comment by LGurtner** [comment]
Just another comment for printing outside the US: In Europe, page formats are different than the default in thesisdown. To adapt the document to A4 pages, include in the YAML header: 
`header-includes:
    - \usepackage[a4paper, total={6in, 8in}, bottom=1in, top = 1in]{geometry}`

The first part sets the pages to A4 format, the 'bottom' and 'top' arguments adjust the margins at the bottom and top of the page.
