### ISSUE TITLE
errors trying to render thesisdown example

### ISSUE THREAD

**Issue by nschiett** [ismayc/thesisdown#125]
Hi, since I updated R, I am not able to render my phd thesis to a pdf. 
I checked if I can render the example of thesisdown, and I noticed that I get errors here as well. 

I get the following error when trying to render the thesisdown example with default output. 

```
! Undefined control sequence.
<argument> @{} >{\centering \arraybackslash 
                                            }p{(\columnwidth - 4\tabcolsep )...
l.607 ...mnwidth - 4\tabcolsep) * \real{0.18}}@{}}

Error: LaTeX failed to compile thesis.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See thesis.log for more info.
```

When trying xelatex (what I actually want to use for my thesis), I get the following error:

```! Package mathspec Error: `amsmath' must be loaded earlier than `mathspec'.```

Any help would be greatly appreciated. I updated tinytex. 

Sessioninfo:
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.7 LTS

Matrix products: default
BLAS:   /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] bookdown_0.21    knitr_1.31       ggplot2_3.3.3   
[4] dplyr_1.0.4      thesisdown_0.1.0 remotes_2.2.0

**Comment by ismayc** [comment]
Hi there. Can you check out this previous issue and see if the change works for you?

https://github.com/ismayc/thesisdown/issues/122

**Comment by JVAQUEROM** [comment]
I downloaded the package in the weekend (Februrary 20th), when the changes were supposed to be merged (am I right?) and getting the error too. 

Also I noticed that, according to the README, you have to include the  Rmd and companion files in an "index" folder. However, all calls to the `here::here` function do not include this `index` in the "folder" argument. So this also prevents knitting.

Thank you for the thesisdown package!!

**Comment by ismayc** [comment]
Please just remove the table from Chapter 3 if you are still having this error.

**Comment by ismayc** [comment]
I’m not following on the `here::here()` issue as `index` is the base for the relative path. Feel free to start a new issue and show the errors so we can diagnose further.

**Comment by nschiett** [comment]
Thanks a lot! Removing the table indeed works! Sorry I missed that previous issue.

**Comment by ismayc** [comment]
No problem! I should probably just remove that table going forward since it is causing more problems than it is really worth.
