### ISSUE TITLE
remove figure description from table of figure

### ISSUE THREAD

**Issue by tkaraouzene** [ismayc/thesisdown#13]
Hi! 
I am using your template and it is very nice. 
However I have an issue with figures. 
I use to put figure title and figure description using chunk label: 
`fig.cap=Fig title : Figure description`.
My issue is that the whole description appears in within the table of figures.
Is there a way to only have figure title ? 
Thanks

PS: Sorry for my poor english, I'm french ;)

**Comment by ismayc** [comment]
You can use the `fig.scap` chunk option to provide a short figure label.  More info is here: https://yihui.name/knitr/options/

**Comment by tkaraouzene** [comment]
Ok thanks ! 
I'm very sorry for the inconvenience I didn't know this option.
My bad...

**Comment by ismayc** [comment]
No problem at all!  There are tons of options that I often have to explore myself.  Thanks for asking!
