### ISSUE TITLE
Captions from \usepackage{subfig} does not align correctly

### ISSUE THREAD

**Issue by bttomio** [ismayc/thesisdown#135]
I am trying to have captions for figures side by side using the package [subfig](https://www.ctan.org/pkg/subfig?lang=en). 

It works very well in a normal RMarkdown file:

![Screenshot from 2021-03-08 15-53-38](https://user-images.githubusercontent.com/44265732/110338105-eb510480-8026-11eb-8892-5d016ba64789.png)

When using {thesisdown}, it somehow does not respect the `fig.subcap` argument. Here is the output:

![Screenshot from 2021-03-08 15-54-20](https://user-images.githubusercontent.com/44265732/110338241-13d8fe80-8027-11eb-80d1-f05e542d00f3.png)

Could you please take a look to see if it is possible to find a solution? Thanks in advance!

-----------

Here are the codes:

**Normal `.Rmd` file**

        ---
        title: "Untitled"
        date: "3/8/2021"
        output: pdf_document
        header-includes:
          - \usepackage{subfig}
        ---
        
        ```{r setup, include=FALSE}
        knitr::opts_chunk$set(echo = TRUE)
        ```
        
        ## Expected result

        ```{r Figures, echo=FALSE, out.width='30%', fig.cap = "Figures", fig.subcap = c("Figure 1", "Figure 2"), fig.align="center"}
        knitr::include_graphics(c("reed.jpg", "reed.jpg"), auto_pdf = T)
        ```

**{ thesisdown}** 

Added to the YAML header:

        header-includes:
          - \usepackage{subfig}

Added to the introduction:

        **Subcaption does not align correctly**
        
        Is it possible to align it?

        ```{r Figures, echo=FALSE, out.width='30%', fig.cap = "Figures", fig.subcap = c("Figure 1", "Figure 2"), fig.align="center"}
        knitr::include_graphics(c("figure/reed.jpg", "figure/reed.jpg"))
        ```

**Comment by ismayc** [comment]
It looks like there is something in either `template.tex` or `reedthesis.cls` that is causing this weird centering since `bookdown::pdf_book` works fine after commenting out the `\backmatter` in the references Rmd. I'm digging in further to see what might be causing this.

**Comment by ismayc** [comment]
If you comment out [line 67](https://github.com/ismayc/thesisdown/blob/503782a4e8e1f534bcdff68a93f4af735526d0a3/inst/rmarkdown/templates/thesis/skeleton/template.tex#L67) and 68 of `template.tex`, it looks like the captions are back to where you'd expect them. Not quite sure of the impact of this in other spots but let me know if that's what you are after.

**Comment by bttomio** [comment]
That works perfectly! Thanks a lot, @ismayc. I should have searched for "caption" in the `template.tex`. I'll be more careful next time before opening an issue. Thanks once again!
