### ISSUE TITLE
Fail to generate pdf using huskydown template

### ISSUE THREAD

**Issue by AFSobral** [ismayc/thesisdown#136]
Hi Chester,
Thank you for providing thesis down!
I am coming to you since I saw you helped solve a similar problem recently in another template generated from thesis down.
I am having a similar error when trying to render huskydown template to pdf, I created an issue, but had no reply:
[https://github.com/benmarwick/huskydown/issues/18](url)

**When I try to render index.Rmd file I get the following:**

processing file: thesis.Rmd
  |...                                                                   |   5%
  ordinary text without R code

  |.......                                                               |  10%
label: include_packages (with options) 
List of 1
 $ include: logi FALSE

  |..........                                                            |  14%
  ordinary text without R code

  |.............                                                         |  19%
label: load (with options) 
List of 1
 $ echo: logi FALSE

  |.................                                                     |  24%
  ordinary text without R code

  |....................                                                  |  29%
label: str
  |.......................                                               |  33%
  ordinary text without R code

  |...........................                                           |  38%
label: load_pkgs (with options) 
List of 2
 $ echo   : logi FALSE
 $ message: logi FALSE

  |..............................                                        |  43%
  ordinary text without R code

  |.................................                                     |  48%
label: speciesinfo (with options) 
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |.....................................                                 |  52%
  ordinary text without R code

  |........................................                              |  57%
label: include_packages_2 (with options) 
List of 1
 $ include: logi FALSE

  |...........................................                           |  62%
   inline R code fragments

  |...............................................                       |  67%
label: unnamed-chunk-1 (with options) 
List of 3
 $ ref.label: chr "include_packages"
 $ results  : chr "hide"
 $ echo     : logi TRUE

  |..................................................                    |  71%
  ordinary text without R code

  |.....................................................                 |  76%
label: unnamed-chunk-2 (with options) 
List of 3
 $ ref.label: chr "include_packages_2"
 $ results  : chr "hide"
 $ echo     : logi TRUE

  |.........................................................             |  81%
   inline R code fragments

  |............................................................          |  86%
label: unnamed-chunk-3 (with options) 
List of 2
 $ echo: logi FALSE
 $ eval: logi FALSE

  |...............................................................       |  90%
  ordinary text without R code

  |...................................................................   |  95%
label: unnamed-chunk-4 (with options) 
List of 1
 $ echo: logi FALSE

  |......................................................................| 100%
  ordinary text without R code

/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS thesis.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output thesis.tex --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/latex-div.lua --metadata-file /var/folders/nf/myc19xfn73z5hkt484xs3xk80000gn/T//RtmpWNFaC3/filee8fc4afe9c74 --self-contained --table-of-contents --toc-depth 3 --template template.tex --number-sections --highlight-style tango --pdf-engine pdflatex --wrap preserve --top-level-division=chapter --include-in-header /var/folders/nf/myc19xfn73z5hkt484xs3xk80000gn/T//RtmpWNFaC3/rmarkdown-stre8fc6a593530.html --variable tables=yes --standalone -Mhas-frontmatter=false --citeproc 
output file: thesis.knit.md

This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
! Emergency stop.
<read *> 

Error: LaTeX failed to compile thesis.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See thesis.log for more info.
In addition: Warning message:
replacing previous import ‘dplyr::pull’ by ‘git2r::pull’ when loading ‘huskydown’ 
Execution halted

**Thesis.log as the following info:**

 ********************************************
 * XeTeX is required to compile this document.
 * Sorry!
 ********************************************

! Emergency stop.
<read *> 
         
l.10 \RequireXeTeX
                   
Here is how much of TeX's memory you used:
 3330 strings out of 480608
 42827 string characters out of 5903630
 285571 words of memory out of 5000000
 19191 multiletter control sequences out of 15000+600000
 532636 words of font info for 25 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 38i,0n,49p,921b,36s stack positions out of 5000i,500n,10000p,200000b,80000s

!  ==> Fatal error occurred, no output PDF file produced!

**Session info:**

xfun::session_info('rmarkdown')
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16, RStudio 1.4.1106

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3   digest_0.6.27     evaluate_0.14     glue_1.4.2       
  graphics_4.0.4    grDevices_4.0.4   highr_0.8         htmltools_0.5.1.1
  jsonlite_1.7.2    knitr_1.31        magrittr_2.0.1    markdown_1.1     
  methods_4.0.4     mime_0.10         rlang_0.4.10      rmarkdown_2.7.2  
  stats_4.0.4       stringi_1.5.3     stringr_1.4.0     tinytex_0.30.1   
  tools_4.0.4       utils_4.0.4       xfun_0.22         yaml_2.2.1       

Pandoc version: 2.11.4

Hope you can help.
Thank you very much in advance.
Best,
Ana

**Comment by ismayc** [comment]
I responded to the issue on {huskydown} you mentioned so hopefully we can track it down and solve it there!
