### ISSUE TITLE
Allow to add `pandoc_args`

### ISSUE THREAD

**Issue by shirdekel** [ismayc/thesisdown#139]
**Describe the bug**
When adding pandoc arguments using `pandoc_args` I get the following error:

```r
Error in bookdown::pdf_book(template = "template.tex", toc = toc, toc_depth = toc_depth,  : 
  formal argument "pandoc_args" matched by multiple actual arguments
```

**To Reproduce**
https://www.loom.com/share/f240c87535f14ecfb3f8fe0ad2b98659

1. Open the `thesisdown` template Rmd 
2. Add a pandoc argument using `pandoc_args`
3. Knit using bookdown::render_book(output_format = "thesisdown::thesis_pdf")

**Expected behavior**
To be able to add extra pandoc arguments.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Firefox
 - Version: 86.0.1 (64-bit)

**Additional context**
I want to add some filters from [`rmdfiltr`](https://github.com/crsh/rmdfiltr), specifically the word count and ampersand filters. I think the issue is that `thesisdown` already specifies `pandoc_args` [here](https://github.com/ismayc/thesisdown/blob/8d551fbcc1c96915e1d58998ab95c8cc901a4739/R/thesis.R#L29). Can `thesisdown` supply the default argument while allowing for extra ones?

**Comment by shirdekel** [comment]
I believe I fixed this in my fork, so I'm happy to submit a PR.

**Comment by ismayc** [comment]
Thanks for digging in! Please do submit a PR
