### ISSUE TITLE
! LaTeX Error: Environment CSLReferences undefined.

### ISSUE THREAD

**Issue by graysonwhite** [ismayc/thesisdown#148]
**Describe the bug**
When attempting to knit my thesis to PDF I received the above LaTeX error. This was after transferring my thesis to a new computer, which has the latest version of `thesisdown` (0.2.0) on it. The thesis knits perfectly on my old computer, which has `thesisdown` 0.1.0 on it.

The error appears to occur when trying to add the references file into the compiled thesis doc. 

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur

**Comment by ismayc** [comment]
Did you also update the template.tex file from the 0.2.0 release? That doesn't happen automatically when you install the new version of the package since I don't want to erase any changes that someone may have made to the template.

**Comment by ismayc** [comment]
Unfortunately pandoc updated over the course of this year which made exactly what you are referring to happen if people were using a different newer version of pandoc.

**Comment by graysonwhite** [comment]
That fixed it. Thanks so much Chester!

**Comment by ismayc** [comment]
You're welcome!
