### ISSUE TITLE
Consider picture as a table

### ISSUE THREAD

**Issue by tkaraouzene** [ismayc/thesisdown#15]
Hi it's me again !
I have some table I retrieved making a screenshot. 
So I would like to know if there is a way to directly include it as a table and not like a figure.
Thanks,
Thomas

**Comment by ismayc** [comment]
Hi Thomas.  Since the table is an image and not a table, they are fundamentally different objects to R Markdown.  I recommend reproducing the table in Markdown/LaTeX and referencing where you obtained the table instead.

**Comment by tkaraouzene** [comment]
Ok thanks for your answer

Le jeu. 16 mars 2017 à 15:41, Chester Ismay <notifications@github.com> a
écrit :
