### ISSUE TITLE
Making changes to template.tex does not affect pdf output

### ISSUE THREAD

**Issue by matanmazor** [ismayc/thesisdown#150]
I tried to edit the template.tex file to make changes to the formatting of the pdf file (e.g., use color links instead of framed links with `\usepackage[colorlinks=true]{hyperref}`). This doesn't change the pdf output. Is there some other file that I should edit?

**Comment by ismayc** [comment]
Potentially reedthesis.cls as well

**Comment by matanmazor** [comment]
Strange, I'm getting 
! LaTeX Error: Option clash for package url.
Even if I make sure to load hyperref in just one of the two files.  Are packages installed from somewhere else as well?

**Comment by ismayc** [comment]
Can you share a reproducible example as requested in the issue template?
