### ISSUE TITLE
when citing same author twice, this is not recognized.

### ISSUE THREAD

**Issue by JVAQUEROM** [ismayc/thesisdown#153]
**Describe the bug**
I am not sure if this is because of the CSL I am using (I do not think so). Sorry for reporting so many issues, I hope I am not being a pain in the neck. Problem is that if I try to cite the same author (different papers) twice, like @Doe2015 and @Doe2016 y get "Doe et al. (2015) and Doe et al. (2016)". But I want "Doe et al. (2015, 2016)". 

**To Reproduce**
Take two papers from same authors and cite then together (I am using citr package). Cite them followed, then they are not detected as same author and writes the same name twice.

**Expected behavior**
I would expect something like Doe et al. (2015, 2016).

**Additional context**
I would like to know if people can reproduce this. It might be an issue of my CSL (but I do not think so). Also, maybe there is some keyword instead of "and" to make thesisdown to work properly with this.

**Comment by ismayc** [comment]
Definitely not a pain in the neck. Sorry for the delay here as I was away for a bit. I'll try to look into this further but it might be a limitation of bibliography/references and I'm not sure how helpful I can be with that.

**Comment by JVAQUEROM** [comment]
Dear @ismayc,

Thank you, I have finaly switched to biblatex. I made my own version of the *.cls (I will upload once I have my thesis finished). With biblatex, citations in parenthesis do not have this issue (someghing like `[@Doe2015 and @Doe2016]`) but not withouth parenthesis, as described in the first message. We should do more tests, definetively, but I think it is a pandoc/bookdown issue.

**Comment by JVAQUEROM** [comment]
Ok, so I just realized it is solved here: #42

Solution is to write it as @Doe2006 [@Doe2008].

I would have to check if it works with the default CSL stuff but I think it will do, so I'll close this
