### ISSUE TITLE
Help to change "chapter" to Spanish 

### ISSUE THREAD

**Issue by aMurryFly** [ismayc/thesisdown#155]
**Describe the bug**
Hi!!! I really  love this project and to be honest I've been working around 1 week to change everything to Spanish but there is just one thing that I couldn't  it  and I really need help :( 

Do you know how to change the word "Chapter", I tried on reeedthesis.cls on line 146 to 166 but if you know how to change that variable I really appreciate it

**Comment by ismayc** [comment]
Hi there! I think you should be able to add

```
\renewcommand{\@chapapp}{Cap\'{\i}tulo}
```

on a line above line 146 of reedthesis.cls to change the chapter name. Hope that works! Let me know if not.

**Comment by aMurryFly** [comment]
OMG !!! It works !!! Thank you so much ! I'm going to finish my thesis as soon as posible to share it ! 

P.S. You're going to be part of acknowledgements !! and thank you again for this amazing project

**Comment by ismayc** [comment]
You're welcome! Best wishes on your continued thesis work. Please let me know when you finish :)
