### ISSUE TITLE
References extra indentation

### ISSUE THREAD

**Issue by eugenesit** [ismayc/thesisdown#157]
**Describe the bug**
An extra indentation is added to all lines in the bibliography, so that the first rows are indented and subsequent rows are doubly indented.

**To Reproduce**
Knit as PDF from a clean install of thesisdown. This behaviour can be observed in the current [example PDF](https://github.com/ismayc/thesisdown_book/blob/master/thesis.pdf).

**Expected behavior**
Only the rows after the first line should be indented, as in an [earlier version](https://github.com/ismayc/thesisdown_book/blob/1d9d238fba28cd5593c5f27953a435b23e85db71/thesis.pdf) of thesisdown.

**Solution**
This issue may have been introduced by the inclusion of hanging indent instructions with CSLEnvironment. Removing indentation formatting from 99-references.Rmd appears to resolve this issue:

```
\setlength{\leftskip}{0.20in}
\setlength{\parskip}{8pt}
```

**Comment by ismayc** [comment]
Thanks again! I've added in this tweak to the `master` template now.
