### ISSUE TITLE
Putting a logo on the front page of the original thesisdown

### ISSUE THREAD

**Issue by Sicily-F** [ismayc/thesisdown#160]
Hi there,

I saw this old issue from a few years ago, and wondered if anyone had figured out how to do this?

I would love to change also the front page, in order to be able to put some university logo. Could you share with me also if you find one solution? Many thanks @KasperSkytte

_Originally posted by @raffdoc in https://github.com/ismayc/thesisdown/issues/17#issuecomment-293922775_

**Comment by KasperSkytte** [comment]
Hi

I just used a plain text front page, I didn't have a nice picture to use anyways. See https://github.com/KasperSkytte/MasterThesis/blob/master/thesis.pdf

**Comment by KasperSkytte** [comment]
The code to produce the report is not included in the repo, but I should be able to dig it up somewhere if you need.

**Comment by Sicily-F** [comment]
that would be amazing, if it's not too much trouble, to see how you specified it to link with thesisdown

**Comment by Sicily-F** [comment]
Sorry - can I just verify, did you use thesisdown, even with the plain text page on the front?

**Comment by KasperSkytte** [comment]
As mentioned here https://github.com/ismayc/thesisdown/issues/17#issuecomment-294482077 I simply adjusted those lines in the `reedthesis.cls` file to this:
```

\renewcommand{\maketitle}{%
  {\pagestyle{empty}
  \fontsize{12}{14}\selectfont
  \begin{titlepage}
  \newpage
  \setcounter{page}{1}
    \begin{center}
        \vspace*{1cm}
        
        \Huge
        \textbf{\@title}
        
        \vspace{0.5cm}
        \LARGE
        Exploring differences in the microbial communities using ordination
        
        \vspace{1.5cm}
        \Large
        Master Thesis in Biotechnology by:\\
        \textbf{\@author}
        
        \vfill
        
        \vspace{0.8cm}
        
        \includegraphics[width=0.4\textwidth]{figure/aaulogo.eps}
        
        \normalsize
        \textit{\@division}\\
        \textbf{Supervisors:}\\
        \@advisor\\
        \@altadvisor\\
        \@date
        
    \end{center}
  \par
  \end{titlepage}

  }
}
```
