### ISSUE TITLE
Front page

### ISSUE THREAD

**Issue by KasperSkytte** [ismayc/thesisdown#17]
Not exactly an issue. Thanks for an awesome template, I'm using it for my master thesis in Biotechnology as I like latex and also have large amounts of data analysis in R. But how can I change the front page? I would like to have a more attractive one than pure text :) Thanks in advance.

**Comment by ismayc** [comment]
You'll need to modify the template.tex file.  Glad you are thinking of using it!  Let me know if I can be of further assistance.

**Comment by raffdoc** [comment]
I would love to change also the front page, in order to be able to put some university logo. Could you share with me also if you find one solution? Many thanks @KasperSkytte

**Comment by KasperSkytte** [comment]
Of course, I'm going to try soon

**Comment by KasperSkytte** [comment]
@ismayc: To change the cover page (titlepage in latex syntax), all there has to be edited are the lines 280-324 in the reedthesis.cls, nothing in template.tex has to be edited, right? It will then grab variables like `\@author` from index.Rmd and its possible to design it as desired, fx based on another [template](https://www.latextemplates.com/cat/title-pages)?

**Comment by ismayc** [comment]
I believe that is correct.  This process is a little finicky.  I'm hoping to try to put together a nicer solution this summer to provide more direction for folks outside of Reed College to be able to use this.  It wasn't intended on first pass to provide that avenue, but I think it makes a logical next step.

**Comment by ismayc** [comment]
You might want to look to see what @zkamvar did to update `thesisdown` for his PhD thesis: https://github.com/zkamvar/beaverdown .
