### ISSUE TITLE
How to add \part ?

### ISSUE THREAD

**Issue by sisbra** [ismayc/thesisdown#179]
Hi, I would like to add parts to the thesis in the following way:
Part I
Chapter 1
Chapter 2
Part II
Chapter 3 (or 1 again)
Chapter 4  (or 2)
However, I could not think of a way to put the latex entry \part into "index" because it is reading automatically the numbered chapters and I could not put it at the beginning of every chapter in their own file, as it leaves 2 blank pages before and 3 blank pages afterwards (with roman numbers). Could you help me? I would be very grateful! 

Thanks for your answer in advance.

Simona

**Comment by ismayc** [comment]
Sorry for the delay here. We did something like this in our ModernDive book. You can see how at https://github.com/moderndive/ModernDive_book/blob/9eeb6f1da90cb7456f0771adf12f643eabab5fe8/02-visualization.Rmd#L1 and on the web at https://moderndive.com/. (Note that I haven't tried this with {thesisdown}, but it does work with {bookdown}.)
