### ISSUE TITLE
Unable to use single quotes in abstract.Rmd

### ISSUE THREAD

**Issue by Samasaur1** [ismayc/thesisdown#184]
_Note: I've already submitted a pull request to fix this bug (#183), but I'm making a corresponding issue as well._

**Describe the bug**
When putting single quotes/apostrophes (`'`) in the `prelims/00-abstract.Rmd` file, `thesisdown` fails to knit. And since the `thesisdown` blank project suggests using the same code for the acknowledgements, dedication, and preface as is used for the abstract, users may face the same issue for those fields.

**To Reproduce**
1. Create a new `thesisdown` project using the instructions in the README
    > 1.  Ensure that you have already installed LaTeX and the fonts described
    above, and are using the latest version of
    [RStudio](https://www.rstudio.com/products/rstudio/download/). You
    can use `thesisdown` without RStudio. For example, you can write the
    Rmd files in your favorite text editor
    (e.g. [Atom](https://atom.io/),
    [Notepad++](https://notepad-plus-plus.org/)). But RStudio is
    probably the easiest tool for writing both R code and text in your
    thesis. It also provides a nice way to build your thesis while
    editing. We’ll proceed assuming that you have decided to use the
    RStudio workflow.
    >
    > 2.  Install the {bookdown} and {thesisdown} packages. Note that
    {thesisdown} is not available on CRAN at the moment and that’s why
    `install.packages("thesisdown")` won’t work. Use
    `remotes::install_github()` as shown below instead to install the
    package.
    >
    > ``` r
    > if (!require("remotes")) 
    >   install.packages("remotes", repos = "https://cran.rstudio.org")
    > remotes::install_github("rstudio/bookdown")
    > remotes::install_github("ismayc/thesisdown")
    > ```
    >
    > Note that you may need to restart RStudio at this point for
the following dialog to show up.
    >
    > 3.  Get started with the {thesisdown} template. There are two options
    for doing so.
    >
    > -   3a) **RECOMMENDED** Create a new RStudio project with a {thesisdown}
    template.
    >
    > In RStudio, click on **File** > **New Project** > **New Directory**.
    Then select **Thesis Project using thesisdown** from the dropdown
    that will look something like the image below. You’ll see the
    graduation cap as the icon on the left for the appropriate project
    type.
    >
    > ![](https://raw.githubusercontent.com/ismayc/thesisdown/master/docs/reference/figures/thesis_proj.png)
    >
    > Next, give your project a name and specify where you’d like the
    files to appear. In the screenshot below, the project name is
    `my_thesis` and it will appear as a new folder on my Desktop.
    >
    > ![](https://raw.githubusercontent.com/ismayc/thesisdown/master/docs/reference/figures/thesis_proj_name.png)
    >
    > If you got this far, skip over step 3b which is the older version of
    getting the template. It might force you to change some of the
    directories to get knitting to work and has some other limitations
    as well. That’s why step 3a is recommended.
    >
    > -   3b) Use the **New R Markdown** dialog to select **Thesis**:
    >
    > ![](https://raw.githubusercontent.com/ismayc/thesisdown/master/docs/reference/figures/thesis_rmd.png)
    >
    > Note that this will currently only **Knit** if you name the
    directory `index` as shown above. This guarantees that `index.html`
    is generated correctly for the Gitbook version of the thesis.
    >
    > 4.  After choosing which type of output you’d like in the YAML at the
    top of `index.Rmd`, **Knit** the `index.Rmd` file to get the book in
    PDF or HTML formats.

1. Edit `prelims/00-abstract.Rmd` to include an apostrophe/single quote
2. Knit again

**Expected behavior**
The project should knit successfully.

**Desktop (please complete the following information):**
 - OS: macOS 12.5
 - `thesisdown`: `master`

**Comment by ismayc** [comment]
Thanks for flagging this. I'm still in the process of reviewing this and understanding any additional implications of the changes.
