### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by paocorrales** [ismayc/thesisdown#193]
Hi, I´m currently writing my thesis using thesisdown and I´d like to cite the package but can´t find any information on how to do it.  Any advise is welcome!

**Comment by ismayc** [comment]
Hi there! Probably something similar to the citation of the `magick` package at https://ropensci.org/blog/2021/11/16/how-to-cite-r-and-r-packages/ would work with the URL being this GitHub repo.

**Comment by paocorrales** [comment]
Thank you for the answer!! And also for the package :)
