### ISSUE TITLE
Page header: overlap between page and "Chapter X"

### ISSUE THREAD

**Issue by andreifoldes** [ismayc/thesisdown#199]
Greetings,
**Describe the bug**
I have one chapter where it seem that there is overcrowding
![image](https://github.com/ismayc/thesisdown/assets/7458009/87838469-c3fe-4018-83c2-2247fcd8dd9c)

**To Reproduce**
Chapter title: Time-dependent consolidation in transitive inference: an RSA approach

**Expected behavior**
Perhaps a line break after "transitive inference:"?

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I would be open to quick and dirty fixes too :)

**Comment by ismayc** [comment]
If you use ChatGPT, I requested some solutions for you at https://chat.openai.com/share/a767e986-fff3-47db-b8ab-8b2e477d7152

**Comment by andreifoldes** [comment]
Thanks! I think what I went with in the end was, adding this to the template.tex file! Basically just reducing the header size, but trying to keep the cool style of alternating between Chapter title and Section title!

```
% Chapter title (small font) on even pages and Section title on odd pages
\fancyhead[LO]{\small\slshape\nouppercase{\leftmark}}   % Odd page: Chapter title on the left (inside)
\fancyhead[RE]{\small\slshape\nouppercase{\rightmark}}  % Even page: Section title on the right (inside)

% Page numbers
\fancyhead[RO]{\thepage}                               % Page number on the right for odd pages (edge)
\fancyhead[LE]{\thepage}                               % Page number on the left for even pages (edge)
```
