### ISSUE TITLE
Chapter bibliography rendering incorrectly in HTML for final chapter

### ISSUE THREAD

**Issue by athowes** [ismayc/thesisdown#201]
**Describe the bug**
I have found that the final chapter of my thesis (HTML output) has a strangely displayed bibliography. It looks like:

<img width="1261" alt="image" src="https://github.com/ismayc/thesisdown/assets/29818116/35fb6aaf-cf87-4df9-9bc4-737478710c01">

(Rather than the text being centred and properly formatted.)

**To Reproduce**
The behaviour is demonstrated in the final chapter of my thesis [here](https://athowes.github.io/thesis/conclusions.html). The source code for my thesis is [here](https://github.com/athowes/thesis).

**Expected behavior**
Correct rendering of the final chapter's references.

**Desktop (please complete the following information):**
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS 14.1.1

(Thank you so much for this package by the way, I look forward to adding my thesis to the examples list! It has made my thesis writing experience much better.)

**Comment by ismayc** [comment]
Hi @athowes. Did this end up working out OK? Apologies for the delay.

**Comment by athowes** [comment]
Hi @ismayc -- yes it appears like it's working now! Apologies, I'm not sure what changed things.
