### ISSUE TITLE
How to knit abstract also.

### ISSUE THREAD

**Issue by raffdoc** [ismayc/thesisdown#24]
Hi, 
I have a question, that I can not figure out by myself. 
How can I force the thesis down to knit also the abstract code when I use pdf version? In gitbook it knits abstract but for pdf there is this expression ``r if(knitr:::is_latex_output()) paste(readLines("00-abstract.Rmd"), collapse = ' ')`` in YAML preamble that I do not know how to change. 
Thanks beforehand.

**Comment by ismayc** [comment]
Can you share your repository or provide a reproducible example with me?  I can't reproduce this error.

**Comment by ismayc** [comment]
You can put your abstract in the file name specified there to have it build the abstract.  Do you have a `00-abstract.Rmd` containing your abstract?

**Comment by raffdoc** [comment]
There is no error produced when I compile pdf file. It just ignores r code in `00-abstract.Rmd`.
In your example YAML you have following comment 
`# If you are creating a PDF you'll need to write your preliminary content here or
# use code similar to line 20 for the files.  If you are producing in a different
# format than PDF, you can delete or ignore lines 20-31 in this YAML header.
abstract: >
  `r if(knitr:::is_latex_output()) paste(readLines("00-abstract.Rmd"), collapse = ' ')``
So I have calculations in my abstract (R code for statistics, etc) that is ignored by the compilation. 
I would like to compile it with knitr. 
Am I clear?

**Comment by ismayc** [comment]
Currently, the abstract for a PDF is designed to not have any R code embedded into it via`readLines`. Can you load your R code in `index.Rmd`?

**Comment by raffdoc** [comment]
You mean the abstract part to YAML header, or in the body of index.Rmd?

**Comment by ismayc** [comment]
Place the R chunk you are loading in the body of the `index.Rmd`.  The `index.Rmd` should load first before the abstract Rmd file.  Additionally you may need to look into the template.tex file or the reedthesis.cls file to ensure that the abstract is being loaded in the spot you wish.

**Comment by raffdoc** [comment]
Dear @ismayc it worked, I just put abstract with r code chunks into the body of `index.Rmd`. 
Than you very much for support.

**Comment by ismayc** [comment]
You're welcome!  Thanks for bringing this up!
