### ISSUE TITLE
Chunks does not behave as one expects they should

### ISSUE THREAD

**Issue by raffdoc** [ismayc/thesisdown#25]
High @ismayc 
I have a problem with chunks. In my first chunk of index.Rmd (which than becomes thesis.Rmd) I have settled my knitr options like this
`knitr::opts_chunk$set(
  fig.path = "figure/", echo = FALSE, out.width='\\textwidth',fig.height=6, fig.width=6
)`
in order to have all other chunks to follow this predefined options, but unfortunately they don't. 
How one can fix this behaviour?
Thanks beforehand.

**Comment by ismayc** [comment]
I am unable to replicate this problem using the default template.  Can you tell me more or share a minimally reproducible example for me to better understand what is going wrong?
