### ISSUE TITLE
How to get only figure labels (1 sentence) instead of full figure legends in List of figures?

### ISSUE THREAD

**Issue by rraadd88** [ismayc/thesisdown#28]
HI @ismayc, 
By default settings, I see that entire figure legends get listed in the `List of figures`. Is there any way that I can only list only the first sentences of figure legends.
I went through the demo [thesis.pdf](https://github.com/ismayc/thesisdown_book/blob/master/thesis.pdf) but couldn't find any discussion on this. May be you may know where and how to tweak the code for this.

**Comment by ismayc** [comment]
Hi @rraadd88.  Use the `fig.scap` chunk option for a short caption on your figure.  More info is at https://yihui.name/knitr/options/ .
