### ISSUE TITLE
Underscores not converted to italics in figure caption

### ISSUE THREAD

**Issue by MorgsJohn** [ismayc/thesisdown#29]
I have not been able to use italics for Latin names in a figure caption when plotting within the r-chunk.  

I have tried:

* `*Ulva*` 
* `_Ulva_` 

`{r plot1, echo=true, fig.align='center', fig.cap="A plot with a scientific name like Ulva", message=FALSE, warning=FALSE, out.width="90%"}
`

Something similar was referred to here:
[knitr#1334](https://github.com/yihui/knitr/issues/1334)

**Comment by nicksolomon** [comment]
Did you try the fix referenced in that knitr issue? Found [here](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references)

**Comment by ismayc** [comment]
@MorgsJohn Any luck with this?

**Comment by ismayc** [comment]
@MorgsJohn I'm closing the issue. Feel free to open it back up if the knitr fix didn't work.
