### ISSUE TITLE
Customize colorlinks when toc = true

### ISSUE THREAD

**Issue by keurcien** [ismayc/thesisdown#32]
Hi again,

Don't know whether you're interested or not, but I thought it would be cool to be able to change the `colorlinks` options the way it can be done with bookdown, directly in the yaml header, since this can't be done with toc = true. Though, it can be done by slightly changing the template.tex, but I would understand if you think it's unnecessary, as people could just tweak the template.tex themselves. Yet if you're interested let me know.

Cheers !

**Comment by ismayc** [comment]
Hi @keurcien.  Is this what your [pull request](https://github.com/ismayc/thesisdown/pull/31) incorporates?

**Comment by keurcien** [comment]
Sorry, my pull requests are pretty badly described, and pretty confusing as well. 
The [pull request](https://github.com/ismayc/thesisdown/pull/31) I have made is not related to this issue, it was actually to give users the possibility to use knitr themes for their chunks. 

About issue #32, what I suggest is to make the LateX internal/citation/URL links customizable (changing the colors). Thought about that because I like to have citations in blue. 

For example, `[@dummy2000]` would now appear like this in my PDF output: (dummy, [2000](https://github.com/ismayc/thesisdown/issues/32)).

Using `toc:true` in `bookdown::pdf_book` along with the original template.tex generates a global `\hypersetup` in the thesis.tex, while it is just defined for the the table of contents, and would thus override any other custom `\hypersetup`.

Here are the corresponding lines:

```
$if(toc)$
  \hypersetup{linkcolor=$if(toccolor)$$toccolor$$else$black$endif$}
  \setcounter{tocdepth}{$toc-depth$}
  \tableofcontents
$endif$
``` 

This could be changed to 

```
$if(toc)$
  {
    \hypersetup{linkcolor=$if(toccolor)$$toccolor$$else$black$endif$}
    \setcounter{tocdepth}{$toc-depth$}
    \tableofcontents
  }
$endif$
``` 

to make the `\hypersetup` local. Then we can define a global `\hypersetup` based on whether the yaml `colorlinks` is set to `true` or not, allowing to customize URLs and citations.

**Comment by ismayc** [comment]
Thanks for clarifying this, @keurcien.  Just adding in the `{` and `}` accomplishes what you are shooting for?

**Comment by keurcien** [comment]
Almost, but we would need to define a global `\hypersetup` that would check the yaml variables:

```
\hypersetup{colorlinks=true,
            linkcolor=$if(linkcolor)$$linkcolor$$else$black$endif$,
            citecolor=$if(citecolor)$$citecolor$$else$black$endif$,
            urlcolor=$if(urlcolor)$$urlcolor$$else$black$endif$}
``` 

Then controlling the colors of the links generated for the list of figures and list of tables the same way it is done for the TOC could be useful:

```
$if(lot)$
  {
    \hypersetup{linkcolor=$if(lotcolor)$$lotcolor$$else$black$endif$}
    \listoftables
  }
$endif$
```

```
$if(lof)$
  {
    \hypersetup{linkcolor=$if(lofcolor)$$lofcolor$$else$black$endif$}
    \listoffigures
  }
$endif$
```
Having all this in the template.tex makes it simpler to set the colors independently, but then again it's not necessary to change your template just for this matter. But it's cool to have this referenced here I assume, so people can get close to the output they want. 

**N.B**: to color the citations, one needs to set `link-citations` to true and set `linkcolor` and **NOT** `citecolor` for some reason.

**Comment by ismayc** [comment]
Ah, I didn't fully understand your tweak.  I'll try to look into this further when I get a chance this week and analyze the implications.
