### ISSUE TITLE
Text style in figure capture

### ISSUE THREAD

**Issue by KleinhansDa** [ismayc/thesisdown#35]
Hi,

First, thanks for this awesome template. I wondered if there's a way to have some text in the figure capture in italics or bold? There should be, no?

I tried...
1. fig.cap="\textit{X.leavis}"
2. fig.cap="_ X.leavis _"
3. fig.cap="* X.leavis *"

but none worked (the latter two without the spaces of course).

Thanks.

**Comment by ismayc** [comment]
Glad you like it! Can you see if this works? https://github.com/rstudio/bookdown/issues/209

**Comment by KleinhansDa** [comment]
Perfect! Thanks.

**Comment by ismayc** [comment]
I’m going to close the issue. Let me know if you have any other related problems by reopening the issue.
