### ISSUE TITLE
Including non-R code and getting a reference

### ISSUE THREAD

**Issue by grmpfhmbl** [ismayc/thesisdown#37]
I have a coupe of code files, that I try to include into my thesis. Basically like a figure, with a caption and reference. I can include the code and it is shown, but does not get a caption etc. 

	```{r examplebash, engine = 'bash', eval = FALSE, code=readLines("examplebash.sh"), fig.cap="Example bash script"}
	```

My question is, is there an easy way to do this? I could basically make screenshots and include them, but as I have a bit more than only 1 or 2 of them, I'd rather have that process kind of automated and less prone to errors. I don't necessarily need a new category - like "listing" - for it. Figure would be sufficient, although I'd be interested in how much efford it would be to achive it.

Could someone point me in the right direction of where my mistake is? Thank you.

**Comment by ismayc** [comment]
I think I would try using a different engine for the chunks you are referring to in different languages: http://rmarkdown.rstudio.com/authoring_knitr_engines.html

**Comment by grmpfhmbl** [comment]
Thank you for your quick answer. I might have poorly expressed my problem and what I wanted to achieve. I do not want to run the code, just display it with syntax highlighting. That's why `eval = FALSE`. But thank you for pointing out the *bash* engine. I'll use that. My problem is: When I use the code above, I see the script file in the PDF output as I want to, but it does not get a caption. It basically looks like that

![pdf-output](https://user-images.githubusercontent.com/5475895/34112415-c92c69f8-e40c-11e7-9818-1c9c74ecb479.png)

The TeX output created by it looks like that

	\begin{Shaded}
	\begin{Highlighting}[]
	\KeywordTok{for} \ExtensionTok{foo}\NormalTok{ in (ls bar)}
	\KeywordTok{do}
	  \BuiltInTok{echo} \VariableTok{$foo}
	\KeywordTok{done}
	\end{Highlighting}
	\end{Shaded}

For example, when I use include_graphics - I am aware that this is an R function that creates the figure -
 in an R script

	```{r img, results="asis", echo=TRUE, fig.cap="A figure", out.width='\\textwidth'}
	include_graphics("./figure/afigure.png")
	```

the TeX output looks like that

	\begin{Shaded}
	\begin{Highlighting}[]
	\KeywordTok{include_graphics}\NormalTok{(}\StringTok{"./figure/afigure.png"}\NormalTok{)}
	\end{Highlighting}
	\end{Shaded}

	\begin{figure}
	\includegraphics[width=\textwidth]{./figure/afigure} \caption{A figure}\label{fig:img}
	\end{figure}

What I basically want to achieve is to get a `\begin{figure} .. \end{figure}` with a label etc around the `\begin{shaded} .. \end{shaded}` part. I thought that this is not an uncommon problem and as I could not find anything on Google I was asking here. The solutions I see at that point are

1. Creating an image by hand and including it with include_graphics(). I don't really like that solution as that is error prone especially when the code changes.
2. I could probably use a [knitr hook](https://yihui.name/knitr/hooks/) and making a new option `echo.asfig`. When this is set, I create the needed TeX before and after the echoed output. Probably the easiest to implement.
3. I could write an R function like "highlight(sourcefile)" that renders the code (using a tool like [prism](http://prismjs.com/) or [highlight](http://www.andre-simon.de/doku/highlight/en/highlight.php)) and then includes the figure using `\include_graphics`. That is probably the solution that takes the most effort to implement and creates dependencies to other (platform dependent) tools - prism for example is written in JavaScript and would need nodeJs to run.

Do you have any suggestions on what other options I may have, or have I just overlooked on how to do it in Rmd?

**Comment by ismayc** [comment]
Ah, thanks for clarifying. I didn't quite understand. I think your best bet here is a knitr hook. Here is a related example though it is using the old Rnw format: https://github.com/yihui/knitr-examples/blob/master/074-example-environment.Rnw

**Comment by grmpfhmbl** [comment]
Thank you. I'll think about it and try around a bit over the next couple of weeks. If I have a solution are you interested in a pull request?

**Comment by ismayc** [comment]
Yes, please!
