### ISSUE TITLE
[pandoc.exe warning] --chapters is deprecated. Use --top-level-division=chapter instead.

### ISSUE THREAD

**Issue by brentthorne** [ismayc/thesisdown#39]
Hello,

Do you have any idea how to fix this error? 

`[pandoc.exe warning] --chapters is deprecated. Use --top-level-division=chapter instead.`

I now am not able to have the temporary thesis.Rmd be deleted after the pdf is created.

Thanks!

**Comment by ismayc** [comment]
I believe this is the same as [this closed issue](https://github.com/ismayc/thesisdown/issues/38)?

**Comment by ismayc** [comment]
On a Windows machine, you should be able to also run

```
# installing/loading the package:
if(!require(installr)) { install.packages("installr"); require(installr)} #load / install+load installr
 
# Installing pandoc
install.pandoc()
```

**Comment by brentthorne** [comment]
Hi @ismayc , that did clear up my issue with the error thank you! Although it still won't remove the temporary thesis.Rmd file and associated files once it has been knit. That is an issue for a different place though, thanks again!

**Comment by ismayc** [comment]
Hmm. Thanks, @brentthorne. Please do create a separate issue. Does similar behavior occur if you try to work directly with `bookdown` instead of `thesisdown`?
