### ISSUE TITLE
No deletion of temporary thesis.Rmd files after knit is completed

### ISSUE THREAD

**Issue by brentthorne** [ismayc/thesisdown#40]
Hello again @ismayc ,

I just wanted to start by saying thank you for reply so quickly to my previous comments!

I have now been able to knit the index.Rmd as a pdf successfully, however once it has completed the deletion of the temporary thesis.Rmd files associated with it does not occur. This means every time I want to re-knit I need to go and delete all of the thesis files that were created previously.

I do not see any warnings in the markdown now that I have updated to Pandoc >=2.0 as you suggested in issue #39 . The only message that appears is:

> `Please delete thesis.Rmd after you finish debugging the error.`

I discovered this issue when returning to my own forked version of [zkamvar's](https://github.com/zkamvar) [beaverdown](https://github.com/zkamvar/beaverdown) called [brockdown](https://github.com/brentthorne/brockdown).

I have tried using [rstudio/bookdown](https://github.com/rstudio/bookdown) but the problem does *not* seem to be occurring.  I worked my way back through thesisdown, beaverdown, and brockdown and they all have the same issue.

Any suggestions?

Thank you.

**Comment by ismayc** [comment]
No problem, @brentthorne! Thanks so much for reaching out.

Maybe you can also dig into the R code to see what is going on behind the scenes in `thesisdown`: https://github.com/ismayc/thesisdown/blob/master/R/thesis.R?

**Comment by brentthorne** [comment]
Okay so I've looked at your [thesis.R](https://github.com/ismayc/thesisdown/blob/master/R/thesis.R) and it appears that the issue goes back to the [render.R](https://github.com/rstudio/bookdown/blob/master/R/render.R) in [bookdown](https://github.com/rstudio/bookdown). 

Looks like Yihui made a change to the way the _bookdown.yaml is named during compiling: https://github.com/rstudio/bookdown/commit/38efc824b23a53c792a68a7e410cd3975faca47d?diff=unified 

So, under the error message from bookdown added the line `delete_merged_file: TRUE` to the [brockdown](https://github.com/brentthorne/brockdown) package [_bookdown.yaml](https://github.com/brentthorne/brockdown/blob/master/inst/rmarkdown/templates/brockuniversity/skeleton/_bookdown.yml) file and it is now working as it was previously. 

Please let me know if you think there may be issues with this solution,

Thanks

**Comment by ismayc** [comment]
Hmm, that makes sense. That looks like a very recent change to `bookdown`. I'd like to wait until this version goes to CRAN before I make any changes here. Does that make sense? I'll leave this issue open.

**Comment by brentthorne** [comment]
Yeah that makes sense to me, I'm worried it may cause problems with people who try and customize the .tex file then try to render afterwords. I guess it will have to be a wait an see situation.

Thanks again!
