### ISSUE TITLE
How update highlight version?

### ISSUE THREAD

**Issue by mavogel** [ismayc/thesisdown#41]
Questions: 
- How is possible to add a new language to `highlight` for the code snippets? 
- Which library is used under the hood? Maybe I can contribute then 😃

**Comment by ismayc** [comment]
Hmm, I’m not sure. I am traveling a bit now. Maybe dig into bookdown/rmarkdown/knitr?

**Comment by mavogel** [comment]
Alright: let's see who answers on [stackoverflow](https://stackoverflow.com/questions/48507307/how-to-add-a-new-language-for-highlight-in-bookdown)
