### ISSUE TITLE
query about generating pdf version

### ISSUE THREAD

**Issue by nicholasjhorton** [ismayc/thesisdown#42]
Is it possible to add a note about how to generate a pdf version of the thesis to README.md?

**Comment by ismayc** [comment]
Hi @nicholasjhorton. Step 4 of the README should do this by pressing the Knit button.

**Comment by nicholasjhorton** [comment]
Ah, but first one needs to comment out 
# thesisdown::thesis_gitbook: default
and uncomment
thesisdown::thesis_pdf: default

Thanks for the quick response: Mine and I are showing this off at our workshop tomorrow.

**Comment by ismayc** [comment]
At some point it would be great to do both at once, but that's a bit tricky at the moment. I suspect that was my original reason for not including this step that you've added in the README. Best wishes in your workshop!
