### ISSUE TITLE
Section numbers using number_sections

### ISSUE THREAD

**Issue by JulioV** [ismayc/thesisdown#45]
Hello,

I would like to have 4 levels of numbers for my sections (e.g. 1.2.3.4). I tried adding number_sections: true to output but it did not work. What is the correct way to supply this parameter?

Thank you

**Comment by ismayc** [comment]
Sorry for the delay here! It somehow fell through the cracks. I believe that bookdown is what is limiting you here. https://github.com/rstudio/bookdown/issues/535

Are you trying to do this with a PDF version only? If so, you might be able to set the LaTeX template accordingly behind the scenes but I haven’t tried this.

**Comment by JulioV** [comment]
I didn't have the chance to try it either, I ended up changing the layout of my document but thanks for the pointer!
