### ISSUE TITLE
skeleton.RMD line number references

### ISSUE THREAD

**Issue by TrashBirdEcology** [ismayc/thesisdown#48]
The various references to line numbers throughout the skeleton.rmd are incorrect. 

Suggest referencing the specific arguments rather than to the line numbers.

**Comment by ismayc** [comment]
Thanks for flagging! PRs appreciated since I won't have a chance to dig into this for a bit.

**Comment by ismayc** [comment]
@TrashBirdEcology Just confirming your updates get to what you were wanting here?

**Comment by TrashBirdEcology** [comment]
yes, v. simple issue! apologies for delayed response

**Comment by ismayc** [comment]
No problem. Thanks!
