### ISSUE TITLE
Template only appears after reloading R session

### ISSUE THREAD

**Issue by JulioV** [ismayc/thesisdown#54]
I created a new package for [UoM](https://github.com/JulioV/uomthesisdown) but after installing it, it only appears under the RMarkdown template list after restarting my R session. Is this something related to the way the package is configured? Thesisdown and [unswthesisdown](https://github.com/rensa/unswthesisdown) don't have this problem.

I'm using RStudio Version 1.2.1335 and R 3.6.0 in Windows x64.

**Comment by ismayc** [comment]
I noticed this same behavior with thesisdown recently on a new computer. It might be something new with RStudio.

**Comment by JulioV** [comment]
I'll keep an eye on this

**Comment by ismailsunni** [comment]
I get the same behavior

**Comment by ismayc** [comment]
Can you share a screencast using useloom.com (no audio needed)? I'd like to be able to understand the workflow others are using.

**Comment by ismailsunni** [comment]
@ismayc 
The workflow is like this:
1. Open RStudio
2. Run the command in the second step `Install the bookdown and thesisdown packages:` from the RStudio console
3. File --> New File --> R Markdown --> From Template
4. The option for the `thesis` is not showing up
5. Restart RStudio, and it will show up

**Comment by ismayc** [comment]
Thanks. I'm finding this is pretty spotty in terms of when it works and when it doesn't with this workflow. Unfortunately, I can't figure out exactly when it occurs and when it doesn't on a variety of different machines. Maybe it makes sense to just update the instructions to request a restart.

**Comment by ismailsunni** [comment]
Yes, I think it's easier to put in the instruction like (e.g. try to restart the RStudio if the option is not showing up) rather than fixing the bug if it's hard to reproduce.

**Comment by ismayc** [comment]
Added a note in [this commit](https://github.com/ismayc/thesisdown/commit/8869cc1da93f725b3b906f626b06556eaa0fb54a#diff-04c6e90faac2675aa89e2176d2eec7d8). Thanks for flagging!
