### ISSUE TITLE
Pandoc cite-proc reference not found after updating Rstudio

### ISSUE THREAD

**Issue by qoldt** [ismayc/thesisdown#55]
~~ I recently upgraded to the new version of Rstudio (which I think has a newer version of pandoc in it) and knitting either html or pdf throws the 
`pandoc-citeproc reference not found` for all of my references.

I tried a minimal example using only bookdown and this worked no problem.

Has anyone else encountered this issue?  
I've tried reinstalling everything and the problem persists. ~~

nevermind. problem in my yaml

**Comment by dennisgrobe** [comment]
I have the same issue but didn't find a way to resolve it. 
I have no problems when knitting a PDF file, but when I choose gitbook as output I get following error message: "pandoc-citeproc: reference xyz not found"

How did you resolve this issue?
