### ISSUE TITLE
White pages between chapters

### ISSUE THREAD

**Issue by BavoKempen** [ismayc/thesisdown#59]
Dear Ismayc,

Firstly, thank you for creating this great spin-off of the bookdown package, I have very much enjoyed working in it. I am currently within the last days of formatting my master's thesis before submitting, however, I have trouble figuring out how to delete white pages generated if a previous chapter did not end on an odd page. Our thesis is in "paper format" and thus these white pages are undesirable in the body. Would it be possible to just limit a white page post title page? I presume \cleardoublepage or \RTcleardoublepage  should be adjusted in the .cls, however due to limited time I do not have the luxury of getting more familiar with the syntax.

Thank you in advance!

Kind regards, 

Bavo

**Comment by Blanchard28** [comment]
Hi @BavoKempen , have you found an answer to your issue? I am also trying to remove the white pages between sections and chapters for my thesis.

**Comment by BavoKempen** [comment]
Hey @Blanchard28 , 

Firstly, sorry for the delayed response since submission I haven't payed attention to GitHub etc. Yes, I changed \documentclass[12pt, **twoside**]{reedthesis} to **oneside** at the top of the LaTeX template to resolve that issue. However, it may remove blank pages between title page and subsequent pages thus manually inserting these within the LaTeX template could help. Not the cleanest solution, however, due to time constraints that worked for me as charm.

Kind regards and good luck!

Bavo Kempen

**Comment by Blanchard28** [comment]
@BavoKempen it worked, thank you so much!
