### ISSUE TITLE
Knit error of initial document

### ISSUE THREAD

**Issue by mb-eco** [ismayc/thesisdown#6]
Hello,

I have just downloaded the thesisdown package and would like to use it for my thesis.
However, when I load a new Rmd file with your template and I try to knit it without changing anything I receive this error message:

Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> ... mapply -> <Anonymous> -> readUTF8 -> readLines -> file
In addition: Warning message:
In file(con, "r") : cannot open file 'index.Rmd': No such file or directory
Execution halted

Do you know what is wrong? And why it does not work?
Thanks a lot.

**Comment by ismayc** [comment]
Note the last line of the README for this repo:  https://github.com/ismayc/thesisdown/blob/master/README.md

**Comment by ismayc** [comment]
You need to name the main driver file index.Rmd. The easiest way to do this is to initially name from folder where you put the materials as index as I showed in the README.
