### ISSUE TITLE
Using alternative to tinytex

### ISSUE THREAD

**Issue by mr-illington** [ismayc/thesisdown#61]
Hello, 

I have been experiencing some issues with knitting my thesisdown to pdf while relying on the tinytex package. Without getting into that topic, I'm rather wondering if it is possible to rely on an alternative source of Latex from knitting? 

Mainly I am thinking this might be possible is as the thesisdown doc reads 

> By far the easiest way to install LaTeX on any platform is with the tinytex R package

But is this the only option? Does the thesisdown package automatically enforce or search for TinyTex alone?

To try it out I have removed TinyTex and installed the full TeX Live for windows, but this is not automatically recognized by my RStudio so far - so would value a little guidance on kniting my thesisdown with the local TeX Live if it's possible.

**Comment by mr-illington** [comment]
To add a bit more context, the error I am currently getting (having removed tinytex and installed full TeX Live in windows) is 

> Error in loadNamespace(name) : there is no package called 'tinytex'
> Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
> Execution haltedv

but there is no traceback or other way to see where tinytext is being called from at the moment so I'm slightly stuck

**Comment by ismayc** [comment]
Hi there. You don't necessarily need to use the R `tinytex` package to work with `thesisdown` but it will automatically install any needed LaTeX packages for you if that comes up as an issue. At what point are you getting that error about `tinytex` not being installed?

**Comment by ismayc** [comment]
I'm not exactly sure how to change the paths to a different LaTeX environment either. This is one reason I really liked `tinytex` as it takes car of this within RStudio.

**Comment by mr-illington** [comment]
Hi ismayc, 

After a bit more digging I've realized my issue is more related to Tinytex install on a corporate machine where the path environment variable has some $$$ in it. 

I've moved the necessary discussion over there. Thanks
