### ISSUE TITLE
Strange include_graphics() behaviour

### ISSUE THREAD

**Issue by mr-illington** [ismayc/thesisdown#62]
Hello, 

Not sure if this could have anything to do with #7, but currently attempting to inserting a full page image with `include_graphics()`. 

I am able bring in the image when I scale it down to 65% using `out.width="60%", out.height="60%"`, but anything above this it simply disappears when the document is knit to pdf. I have also experimented with this as both a .png and a .pdf to no effect.  

The image is an A4 map, and my goal is to use as much of the available space within the margins as possible to display the map. Therefore I currently start a new page right before the `include_graphics()` chunk using `\newpage`.

As I understand it, image scaling with dpi argument should not matter, as it should be over-written by my `out.width` argument. 

Not sure what to try next, but feeling like I might be missing a certain chunk argument or something similar to get the desired result?

Any general advice on how to get a splashy full page graphic here and there (ideally over the top of the page number for that page) but still with a figure caption that can be linked to would be most appreciated! I am working with huwiwidown for reference.

**Comment by ismayc** [comment]
Hello. I’ve also had trouble tweaking image sizes. [This](https://stackoverflow.com/questions/39053478/how-do-i-rescale-local-images-for-bookdown-rmarkdown-website) StackOverflow link might be helpful, but it might be best to head to the knitr repo and file an issue there.

**Comment by ismayc** [comment]
Hi @mr-illington. Did you have any luck on the {knitr} side here?
