### ISSUE TITLE
Including 'abstract' into yaml header causes a bunch of various errors

### ISSUE THREAD

**Issue by christianholland** [ismayc/thesisdown#63]
Hi,

first of all thank you very much for providing a skeleton to write my thesis with bookdown.

I figured out that line 22-23 of the `index.Rmd` lead to various errors when knitting the file as a gitbook:

```
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-abstract.Rmd"), collapse = '\n  ')`
```

```
[WARNING] Could not parse YAML metadata at line 44 column 1: :23:0: leading empty lines contain more spaces than the first non-empty line in scalar
pandoc-citeproc: reference Molina1994 not found
pandoc-citeproc: reference reedweb2007 not found
pandoc-citeproc: reference noble2002 not found
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'thesis.utf8'
```
Especially the second warning is critical as it removes the information about title, author and date from the gitbook. Hence, it starts directly with `Introduction` 

Removing line 22-23 solves these problem (but is at least for me not an option to solve this issue)

Thanks,
Christian

**Comment by ismayc** [comment]
Thanks for reporting, Christian. I'm still digging into what might be causing this change and hope to have an answer for you this week.

**Comment by ismayc** [comment]
[My comment on line 20](https://github.com/ismayc/thesisdown/blob/8869cc1da93f725b3b906f626b06556eaa0fb54a/inst/rmarkdown/templates/thesis/skeleton/skeleton.Rmd#L20) does suggest that one doesn't try to build the gitbook with the lines below it "on", but that's not necessarily clear. I think it's probably best that I switch to having specific files be used for the PDF and gitbook versions similar to what I did with the ModernDive book [here](https://github.com/moderndive/ModernDive_book/blob/master/_bookdown.yml). If you think that makes sense as well, let me know and I can get to working on changing it over.

**Comment by christianholland** [comment]
Thanks for tackling my issue. 

For me it feels a bit redundant to specify almost exactly the same files for the different output types, but if this is working I am happy to use it.

My only concern is about the pdf output. So far some files (e.g. abstract, acknowledgement, prefect, etc...) are passed from the yaml header in `index.Rmd` to `preamble.txt` where they are integrated in their respective environment:


```
preface: |
  This is an example of a thesis setup to use the reed thesis document class
  (for LaTeX) and the R bookdown package, in general.
```

to

```
\Preface{
$preface$
}
```

How will this work when you specify all files in `_bookdown.yaml`? Will you still be able to pass them to the `preamble.txt`?

**Comment by ismayc** [comment]
The setup that you mentioned only really works with the PDF version, so the HTML version will need to include `00--prelim.Rmd` as a file to use before `index.Rmd` in `_bookdown.yml`. If we can figure out a way to have the Preface and other non-main matter content work nicely with both HTML and LaTeX in the YAML, that's the best case scenario. Unfortunately, I couldn't figure out such a way in the past to incorporate the YAML to work with both.

One alternative is to remove the YAML specifying of this intro content and force everything to appear in their own Rmd files or we could just put the content in the `index.Rmd` file to force it to appear in the correct spot and that will also work with both the HTML and LaTeX versions.

Complicated stuff :smile:

**Comment by christianholland** [comment]
I found a repo that uses an adapted version of your `thesisdown` package (https://github.com/lazappi/phd-thesis; https://github.com/lazappi/unimelbdown). Checking the `gitbook` version of the thesis (https://lazappi.github.io/phd-thesis/) indicates that @lazappi might have found a way to make it work. At least title, author and date appear correctly. Maybe @lazappi is willing to help

PS: Does tagging work across repositories?

**Comment by lazappi** [comment]
I'm not sure if I came up with a different solution. I used the YAML fields for the PDF version and have this file which adds them to the HTML/DOCX versions https://github.com/lazappi/phd-thesis/blob/master/0-frontmatter/00-frontmatter.Rmd.

Not sure if that is useful or not. I'm a bit rusty on how this all works now but happy to help if I can.

**Comment by ismayc** [comment]
Thanks, @lazappi. It doesn't seem that there is a clean solution here. Maybe it's best to just remove the YAML introductory content for the {thesisdown} template? That way specifying them in the index.Rmd file will transfer nicely over to all the various output formats (PDF, Gitbook, Word, etc.)?

**Comment by jcrodriguez1989** [comment]
Hi, sorry I come with another issue, but by googling I note that @christianholland is having the same (other) issue as me:
```
pandoc-citeproc: reference Molina1994 not found
pandoc-citeproc: reference reedweb2007 not found
pandoc-citeproc: reference noble2002 not found
```

there is no way I can get references for the gitbook version, however for the pdf version it is working like a charm. This is happening with the fresh thesisdown example, and also with my repo https://github.com/jcrodriguez1989/tesis_doctoral/

Any idea?
thanks!

**Comment by ismayc** [comment]
Hi @jcrodriguez1989. I think it's probably best that I just remove the option to include the introductory material in YAML as I suggested in [the comment above](https://github.com/ismayc/thesisdown/issues/63#issuecomment-564099590). I'll try to get this figured out over the next few weeks if that's OK with you.

**Comment by jcrodriguez1989** [comment]
Wow, I thought that commenting those lines would fix the "[WARNING] This document format requires a nonempty <title> element." issue.
Now, I have tried it again, and I'm getting the cites correctly.
thanks @ismayc , great package! ;)

**Comment by franzbischoff** [comment]
I dunno if this was solved, but, for me the issue was solved when I removed the first space before "`":

```
abstract: |
 `r if(knit .....
```

**Comment by ismayc** [comment]
Yep. The most up-to-date version of the package template removes the extra line all together: https://github.com/ismayc/thesisdown/blob/2f14a725d0e9ccbf1ff625f62e489fdec07349b6/inst/rmarkdown/templates/thesis/skeleton/skeleton.Rmd#L32

**Comment by daynefiler** [comment]
> Yep. The most up-to-date version of the package template removes the extra line all together:
> 
> https://github.com/ismayc/thesisdown/blob/2f14a725d0e9ccbf1ff625f62e489fdec07349b6/inst/rmarkdown/templates/thesis/skeleton/skeleton.Rmd#L32

Of note, the above removes line breaks, whereas the single space solution above does not. This was a VERY helpful thread.
