### ISSUE TITLE
How can I delete the automatic designation of the Chapters as "Chapter #" for the .pdf output

### ISSUE THREAD

**Issue by dennisgrobe** [ismayc/thesisdown#64]
Hi,

first of all thank you very much for providing a template to write my thesis with bookdown.

I struggle with the automatic designation of the Chapters in the pdf output. 
I managed to turn it of for knitting to gitbook by deleting the chapter section in the "_bookdown.yml" file.

I also managed to turn off the automatic designation of the chapters in the table of contents of the pdf file by deleting this part of the reedthesis.cls file:

\def\@chapter[#1]#2{\ifnum \c@secnumdepth >\m@ne
                       \if@mainmatter
                         \refstepcounter{chapter}%
                         \typeout{\@chapapp\space\thechapter.}%
                         \addcontentsline{toc}{chapter}%
                         {\@chapapp\space\thechapter:\space#1}%
                       \else
                         \addcontentsline{toc}{chapter}{#1}%
                       \fi
                    \else
                      \addcontentsline{toc}{chapter}{#1}%
                    \fi
                    \chaptermark{#1}%
                    \addtocontents{lof}{\protect\addvspace{10\p@}}%
                    \addtocontents{lot}{\protect\addvspace{10\p@}}%
                    \if@twocolumn
                      \@topnewpage[\@makechapterhead{#2}]%
                    \else
                      \@makechapterhead{#2}%
                      \@afterheading
                    \fi}

But somehow the Chapters begin with "Chapter #" and i don't know where to change that for the .pdf file

Can someone help me with this issue?

**Comment by ismayc** [comment]
Hi @dennisgrobe. I'm not quite sure how to help, but maybe it's best to try one of the variants of the package that use a different CLS file than the reedthesis.cls, which is pretty customized. You can find the list at https://github.com/ismayc/thesisdown#customizing-thesisdown-to-your-institution.

**Comment by dennisgrobe** [comment]
Hey @ismayc . Thanks for your answer, but i didn't want to start working with a new CLS file because i have already made some changes to my file. But i've just worked it out ;-)


By default, your LaTeX document has Chapter name (Chapter 1, Chapter 2, etc.) for each chapter.
If you want to remove such chapter name from your document, then you can use titlesec package and define the titleformat in order to hide the chapter title.

I added the following code to the CLS file: 

`\usepackage{titlesec}
 \usepackage{lipsum}
 % Title with chapter number  
\titleformat{\chapter}[hang]
  {\normalfont\bfseries\huge\raggedright}
  {\thechapter }
  {15pt}
  {\Huge}  
% Alternative Title without chapter number  
%\titleformat{\chapter}[display]
%  {\normalfont\bfseries}{}{0pt}{\Huge}  `

**Comment by dennisgrobe** [comment]
Anyway thank you very much for your really fast answer!! :D

**Comment by ismayc** [comment]
Ah! Very good. My LaTeX is getting rusty so it's great to see this as the tweak needed. Happy to help!
