### ISSUE TITLE
Large Images not scaled

### ISSUE THREAD

**Issue by Brueni92** [ismayc/thesisdown#7]
Hi there,

Thank you for your template, looks great. I encountered the issue that .png's and .jpg's files are no scaled and therefore just continued over the edge...

I solved the issue adding this line to your template:
\setkeys{Gin}{width=\linewidth}

Best regards

**Comment by ismayc** [comment]
I wanted to leave the option for users to scale their images as they wished since some may not want their smaller images to be the width of the page.
