### ISSUE TITLE
Bibliography in PDF but not gitbook

### ISSUE THREAD

**Issue by oliviaAB** [ismayc/thesisdown#70]
Hi,

Thanks for this great package! I've been having trouble with the bibliography: when I knit a PDF the citations appear as expected, although at the beginning of the References section the word "placeholder" shows up before the first reference even though I can't find it anywhere in the templates or any of my files. However when I knit as a gitbook all the citations appear as ??? and the References section is empty. Not sure what I'm doing wrong...

Thanks for your help!

**Comment by ismayc** [comment]
Hi Olivia. Thanks much for the kind words. Unfortunately I’m not able to reproduce your error. Could you share a minimally reproducible example? Feel free to email me at chester.ismay AT gmail.com if you’d prefer to share the files with me there.

**Comment by oliviaAB** [comment]
Thank you very much for your quick answer! I'll send you the files right now.

**Comment by oliviaAB** [comment]
Hi,
I figured out that the "placeholder" problem comes from the fact that very stupidly I hit the knit button from one of the chapter instead of from the index.Rmd file. My bad :)
Second, I think the bibliography issue comes from my computer and not the files in themselves. I haven't figured out what causes it but I'll investigate. 
Sorry for the trouble!

**Comment by ismayc** [comment]
No problem! I'm glad you figured it out. I wasn't having any luck reproducing on my end so I'm glad you were able to drill down on what was happening. Thanks for keeping me updated!
