### ISSUE TITLE
Can Not Knit to PDF from Terminal

### ISSUE THREAD

**Issue by ismailsunni** [ismayc/thesisdown#71]
Hi, I am trying to use the terminal instead of RStudio's knit to build the PDF. I run this command to do it:

```bash
Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'
```

Unfortunately, I got this error:
```
/usr/bin/pandoc +RTS -K512m -RTS thesis.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output thesis.tex --table-of-contents --toc-depth 2 --template /home/ismailsunni/R/x86_64-pc-linux-gnu-library/3.6/rmarkdown/rmd/latex/default-1.17.0.2.tex --number-sections --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable 'geometry:margin=1in' --variable 'compact-title:yes' --include-in-header /tmp/Rtmppe41Um/rmarkdown-str2c4377d9ac86.html --variable tables=yes --standalone --filter /usr/bin/pandoc-citeproc 
! Undefined control sequence.
l.1203 \backmatter

Error: Failed to compile thesis.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See thesis.log for more info.
Execution halted
```

It's strange because I can knit it from RStudio just fine.

Is there any special setting or command to knit to PDF from the terminal?

Thanks!

**Comment by ismayc** [comment]
I’m not exactly sure since you are using {bookdown} here instead of {thesisdown}. Could you file an issue on the bookdown repo instead? It’s probably best to share the files you are trying to build too if possible.

**Comment by ismailsunni** [comment]
Hi @ismayc 
Sorry, I am not clear here.
So, I am writing my thesis with your `thesisdown`. My thesis is in this [repo](https://github.com/ismailsunni/MasterThesis/). If you want to try, you can clone it for sure.

I usually use RStudio to knit it to PDF. I want to knit to PDF from the terminal. It should be possible, right?

I tried to run :
```bash
Rscript -e 'library("thesisdown"); thesisdown::thesis_pdf()'
```

But it seems not the correct thing. What should I run to knit from the terminal?

Thanks!

**Comment by ismayc** [comment]
I've never tried to do this from the terminal. I'll try to figure out what might be going on here, but I'm not sure when I'll have a chance to.

**Comment by ismailsunni** [comment]
@ismayc thanks! no rush :)

**Comment by ismayc** [comment]
I just tried `Rscript -e 'bookdown::render_book("index.Rmd", "thesisdown::thesis_pdf")'` and that works for me. Can you try that?

**Comment by ismailsunni** [comment]
Hi @ismayc 
Thanks, it works :)
