### ISSUE TITLE
Installing thesisdown in R 3.6

### ISSUE THREAD

**Issue by Rcubes** [ismayc/thesisdown#73]
Hi guys, I´m having this issue to install thesisdown:

"package 'dplyr' was built under R version 3.6.2"

I´ve tried downgrading dplyr, reinstalling several other packages but this error keeps coming up. Is there any way I can work this around to sucessfully install thesisdown? I´m super interested in this package since I really need to write my thesis.
I also noticed someone had a similarly issue when R 3.6 came out and the issue solved when moving to R 3.6.1, I tried downgrading R but it didn't work either.

Thanks,

**Comment by ismayc** [comment]
Hello. Could you please share your `sessionInfo()` or `devtools::session_info()`? This error usually means that you should update your R to version 3.6.2.

**Comment by ismayc** [comment]
Alternatively, you might be able to try installing a previous version of {dplyr} by running `remotes::install_version("dplyr", "0.8.3")`.

**Comment by Rcubes** [comment]
I ran the sessionInfo, getting the following:

- Session info -------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Spanish_Chile.1252          
 ctype    Spanish_Chile.1252          
 tz       America/Santiago            
 date     2020-02-12                  

- Packages -----------------------------------------------------------------------------------------
 package     * version    date       lib source                    
 assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.1)            
 backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.1)            
 bookdown      0.17       2020-01-11 [1] CRAN (R 3.6.2)            
 callr         3.4.1      2020-01-24 [1] CRAN (R 3.6.2)            
 cli           2.0.1.9000 2020-02-11 [1] Github (r-lib/cli@e9f041e)
 crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.1)            
 curl          4.3        2019-12-02 [1] CRAN (R 3.6.2)            
 desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.1)            
 devtools      2.2.1      2019-09-24 [1] CRAN (R 3.6.1)            
 digest        0.6.23     2019-11-23 [1] CRAN (R 3.6.1)            
 ellipsis      0.3.0      2019-09-20 [1] CRAN (R 3.6.1)            
 evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.1)            
 fansi         0.4.1      2020-01-08 [1] CRAN (R 3.6.2)            
 fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.1)            
 glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.1)            
 htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.1)            
 knitr         1.28       2020-02-06 [1] CRAN (R 3.6.2)            
 magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.1)            
 memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.1)            
 packrat       0.5.0      2018-11-14 [1] CRAN (R 3.6.1)            
 pkgbuild      1.0.6      2019-10-09 [1] CRAN (R 3.6.1)            
 pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.1)            
 prettyunits   1.1.1      2020-01-24 [1] CRAN (R 3.6.2)            
 processx      3.4.2      2020-02-09 [1] CRAN (R 3.6.2)            
 ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.1)            
 R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.1)            
 Rcpp          1.0.3      2019-11-08 [1] CRAN (R 3.6.1)            
 remotes       2.1.0      2019-06-24 [1] CRAN (R 3.6.1)            
 rlang         0.4.4      2020-01-28 [1] CRAN (R 3.6.2)            
 rmarkdown     2.1        2020-01-20 [1] CRAN (R 3.6.2)            
 rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.6.1)            
 rstudioapi    0.11       2020-02-07 [1] CRAN (R 3.6.2)            
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.1)            
 testthat      2.3.1      2019-12-01 [1] CRAN (R 3.6.2)            
 usethis       1.5.1      2019-07-04 [1] CRAN (R 3.6.1)            
 withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.1)            
 xfun          0.12       2020-01-13 [1] CRAN (R 3.6.2)            
 yaml          2.2.1      2020-02-01 [1] CRAN (R 3.6.2)            

[1] C:/Users/fata2810/Documents/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.1/library
> 
Currently I have R 3.6.2, I tried the approach of downgrading to an older version of dplyr, and first remotes ask to update dplyr, when skipping that option I got this:

Failed to install 'thesisdown' from GitHub:
  (convertido del aviso) installation of package ‘C:/Users/fata2810/AppData/Local/Temp/1/RtmpuKL2TY/filee4065cd760e/thesisdown_0.0.3.tar.gz’ had non-zero exit status

Not sure if this makes sense to you or there is something else I could try to make thesisdown work.

Thanks in advance,

Alfonso

**Comment by ismayc** [comment]
Based on what you just shared above with your sessionInfo, it looks like you are running R 3.6.1 instead of R 3.6.2. Could you please remove your previous versions of R and make sure you upgrade to 3.6.2?

**Comment by Rcubes** [comment]
It worked, combining downgrading dplyr to 0.8.3 and downgrading R 3.6.1. Initially I had tried downgrading R and separately downgrading dplyr. 

I´m expecting this can soon be fully compatible with R 3.6.2 especially because dplyr 1.0.0 is approahing. 

Thanks for your help,

Alfonso
