### ISSUE TITLE
Not able to install 'thesisdown'

### ISSUE THREAD

**Issue by marcecevallos** [ismayc/thesisdown#83]
Hi, I have been trying to download your package with no luck. The error is not very informative as states that the package had a non-zero exit status.
However I have Latex through tinytex and pandoc.
Any suggestion?

**Error image**
![image](https://user-images.githubusercontent.com/51297505/82200517-63ff9c80-98ff-11ea-85f4-34943ad6c07f.png)

**Session info**
![image](https://user-images.githubusercontent.com/51297505/82200650-90b3b400-98ff-11ea-821c-24e2f86527cf.png)

**Comment by ismayc** [comment]
Can you try to install the {remotes} package again via `install.packages(“remotes”)` and then do `remotes::install_github(“ismayc/thesisdown”)`?

**Comment by marcecevallos** [comment]
Thank you for your fast answer, while trying to re-install via install.packages('remotes') the package was updated and using it again with the remotes::install_github(“ismayc/thesisdown”)  ended in the same result

![image](https://user-images.githubusercontent.com/51297505/82211092-94036b80-9910-11ea-917c-0570fdef8eed.png)

**Comment by ismayc** [comment]
You’re welcome! Something that should work is to update R to version 3.6.3 or later, but I don’t think you should have to do that to install this package. I can try to look into this further later on this week if that’s an OK timeline for you.

**Comment by marcecevallos** [comment]
Yes sure! I have still until  august to write my thesis :) I will be very appreciated 
Btw my R is version 3.6.3 so maybe there is a deeper issue for me Thank u

**Comment by ismayc** [comment]
Hmm, maybe restart R? A previous screenshot you sent had you on R 3.6.0.

**Comment by marcecevallos** [comment]
So, a little update hehe I decided to take my chances and install R 4.0.0, had a little issue with backports but I solved it and 
![image](https://user-images.githubusercontent.com/51297505/82228045-e3559600-9928-11ea-8fd1-53d53857a70e.png)

It installed :) I was a bit cautious of updating R because of the libraries but it worked 
![image](https://user-images.githubusercontent.com/51297505/82228162-10a24400-9929-11ea-9cc3-061c06031877.png)


Thank you

**Comment by ismayc** [comment]
You’re welcome! Glad you got it working.
