### ISSUE TITLE
Warnings in skeleton

### ISSUE THREAD

**Issue by mmahmoudian** [ismayc/thesisdown#86]
I followed the instructions to create the "index" folder and then immediately without changing anything I hit "knit" in Rstudio and then at the end of the gitbook generation I got this:

> ```
> Output created: _book/thesis.pdf
> Warning message:
> Package Fancyhdr Warning: \headheight is too small (12.0pt): 
> Make it at least 14.49998pt.
> We now make it that large for the rest of the document.
> This may cause the page layout to be inconsistent, however. 
> ```

and then I switched to `thesisdown::thesis_gitbook` by commenting [line 15](https://github.com/ismayc/thesisdown/blob/f0a1acd7bf015e7c1e4904225cd84e24b178c56d/inst/rmarkdown/templates/thesis/skeleton/skeleton.Rmd#L15) and uncommenting [line 16](https://github.com/ismayc/thesisdown/blob/f0a1acd7bf015e7c1e4904225cd84e24b178c56d/inst/rmarkdown/templates/thesis/skeleton/skeleton.Rmd#L16) and I got this (not adding any character to the yml file and just moving `#` from line 15 to line 16):

> ```
> [WARNING] Could not parse YAML metadata at line 44 column 1: :23:0: leading empty lines contain more spaces than the first non-empty line in scalar
> pandoc-citeproc: reference Molina1994 not found
> pandoc-citeproc: reference reedweb2007 not found
> pandoc-citeproc: reference noble2002 not found
> [WARNING] This document format requires a nonempty <title> element.
>   Please specify either 'title' or 'pagetitle' in the metadata.
>   Falling back to 'thesis.utf8'
> ```

The following is the output of `sessionInfo()`:

> ```
> R version 3.6.0 (2019-04-26)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 18.04.4 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=fi_FI.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=fi_FI.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=fi_FI.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=fi_FI.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.4.6      rstudioapi_0.11   knitr_1.28       
>  [4] R6_2.4.1          rlang_0.4.6       fansi_0.4.1      
>  [7] tools_3.6.0       pkgbuild_1.0.8    packrat_0.5.0    
> [10] xfun_0.14         cli_2.0.2         withr_2.2.0      
> [13] htmltools_0.4.0   remotes_2.1.1     rprojroot_1.3-2  
> [16] yaml_2.2.1        digest_0.6.25     assertthat_0.2.1 
> [19] crayon_1.3.4      bookdown_0.19.1   processx_3.4.2   
> [22] callr_3.4.3       ps_1.3.3          curl_4.3         
> [25] glue_1.4.1        evaluate_0.14     rmarkdown_2.1    
> [28] compiler_3.6.0    backports_1.1.7   prettyunits_1.1.1
> [31] thesisdown_0.0.3 
> ```

**Comment by ismayc** [comment]
Hmm, I think this might be due to trying to include some of the preliminary content in the YAML instead of their own Rmd files, but I'm not sure. This will likely require an update to the package to fix this, though I'm not exactly sure if that's what is causing this.

**Comment by mmahmoudian** [comment]
Let me know what you want to test and I'll do it and will report back. The question I have is that can you reproduce this using the same environment?

**Comment by ismayc** [comment]
There have been some weird things happening with the HTML build for awhile now so I don’t think it is anything specific to what versions you are using. I have some time blocked off this week to try to investigate further.

**Comment by ismayc** [comment]
Can you try out `remotes::install_github("ismayc/thesisdown", ref = "develop")`. I believe all the warnings you brought forth should be cleared up now there.

**Comment by mmahmoudian** [comment]
Confirmed. Warnings in both `thesis_pdf` and `thesis_gitbook` are now gone.
