### ISSUE TITLE
package ‘thesisdown’ is not available (for R version 4.0.2)

### ISSUE THREAD

**Issue by hao203** [ismayc/thesisdown#98]
When I try to install through install.packages("thesisdown"), it prompted the error package ‘thesisdown’ is not available (for R version 4.0.2) in Rstudio.

**Comment by ismayc** [comment]
Hi. Please follow the [instructions on the README](https://github.com/ismayc/thesisdown#using-thesisdown-from-chesters-github) for installing. As noted there, this package is not yet on CRAN and that’s why you are receiving this error.

**Comment by hao203** [comment]
> Hi. Please follow the [instructions on the README](https://github.com/ismayc/thesisdown#using-thesisdown-from-chesters-github) for installing. As noted there, this package is not yet on CRAN and that’s why you are receiving this error.
When I ran remotes::install_github("ismayc/thesisdown"), it failed.
Failed to install 'unknown package' from GitHub:
  schannel: failed to receive handshake, SSL/TLS connection failed

**Comment by ismayc** [comment]
Hi there. Are you behind a proxy? Can you install a different package via GitHub, say `remotes::install_github(“yihui/knitr”)`? Does that provide the same error?

**Comment by hao203** [comment]
> Hi there. Are you behind a proxy? Can you install a different package via GitHub, say `remotes::install_github(“yihui/knitr”)`? Does that provide the same error?


Thanks. It's about the damn Chinese internet. I solved the problem by VPN.

**Comment by ismayc** [comment]
Great! I’m glad you got it figured out. I hope you enjoy using the package.
